# =================================================================================================
#     Reference Genome
# =================================================================================================

genome: ../Data/Refrence/MTHFR_Gene.fasta
idx: 


# =================================================================================================
#     Directory Paths
# =================================================================================================
paths:
  genomepath: ../Data/Refrence
  samples_path: ../Data/Samples
  mapped_reads: ../Data/Mapped_Reads
  vcfs: ../Data/VCFs
  output: ../Data/output
  mpileup: ../Data/mpileup

# =================================================================================================
#     Indexing params
# =================================================================================================
bwa:
  index: bwtsw

# =================================================================================================
#     samtools options 
# =================================================================================================

output: ../Data/output/merged.bcf

# =================================================================================================
#     samtools options 
# =================================================================================================


# To call from this file you basicaly put brackets until you reach the variable you need
# ex: in the params part use [ref][fasta], then call it with params.x
